--//Preppin' Data
//2023: Week 6


--Output

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID),
    CTE2 AS (SELECT CTE.CUSTOMER_ID,
                    CTE.CATEGORY,
                    "'MOBILE_APP'" "MOBILE APP",
                    "'ONLINE_INTERFACE'" "ONLINE INTERFACE",
                    AVG("MOBILE APP") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING MOBILE APP",
                    AVG("ONLINE INTERFACE") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING ONLINE INTERFACE",
                    "AVERAGE RATING MOBILE APP" - "AVERAGE RATING ONLINE INTERFACE" "DIFFERENCE IN AVERAGE RATING"
            FROM CTE
            PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
            WHERE CATEGORY <> 'OVERALL_RATING'
            GROUP BY 1,2,3,4
            ORDER BY CUSTOMER_ID),
    CTE3 AS (SELECT CUSTOMER_ID,
                    "DIFFERENCE IN AVERAGE RATING",
                    CASE 
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 2 THEN 'Mobile App Superfan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 1 THEN 'Mobile App Fan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 0 THEN 'Neutral'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= -1 THEN 'Online Interface Fan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= -2 THEN 'Online Interface Superfan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= 0 THEN 'Neutral'
                    END "Preference"
            FROM CTE2
            GROUP BY ALL)
SELECT "Preference",
        ROUND((COUNT(CUSTOMER_ID) / (SELECT COUNT(CUSTOMER_ID)
                              FROM CTE3) *100) , 1) "% of Total"
FROM CTE3
GROUP BY 1
ORDER BY 2 DESC
;



--Reshape the data so we have 5 rows for each customer, with responses for the Mobile App and Online Interface being in separate fields on the same row
--Clean the question categories so they don't have the platform in from of them
----e.g. Mobile App - Ease of Use should be simply Ease of Use

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID)
SELECT *
FROM CTE
PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
;



--Exclude the Overall Ratings, these were incorrectly calculated by the system

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID)
SELECT *
FROM CTE
PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
WHERE CATEGORY <> 'OVERALL_RATING'
ORDER BY CUSTOMER_ID
;



--Calculate the Average Ratings for each platform for each customer 

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID)
SELECT CTE.CUSTOMER_ID,
        CTE.CATEGORY,
        "'MOBILE_APP'" "MOBILE APP",
        "'ONLINE_INTERFACE'" "ONLINE INTERFACE",
        AVG("MOBILE APP") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING MOBILE APP",
        AVG("ONLINE INTERFACE") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING ONLINE INTERFACE"
FROM CTE
PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
WHERE CATEGORY <> 'OVERALL_RATING'
GROUP BY 1,2,3,4
ORDER BY CUSTOMER_ID
;



--Calculate the difference in Average Rating between Mobile App and Online Interface for each customer

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID),
    CTE2 AS (SELECT CTE.CUSTOMER_ID,
                        CTE.CATEGORY,
                        "'MOBILE_APP'" "MOBILE APP",
                        "'ONLINE_INTERFACE'" "ONLINE INTERFACE",
                        AVG("MOBILE APP") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING MOBILE APP",
                        AVG("ONLINE INTERFACE") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING ONLINE INTERFACE"
            FROM CTE
            PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
            WHERE CATEGORY <> 'OVERALL_RATING'
            GROUP BY 1,2,3,4
            ORDER BY CUSTOMER_ID)
SELECT CUSTOMER_ID, 
        "AVERAGE RATING MOBILE APP" - "AVERAGE RATING ONLINE INTERFACE" "DIFFERENCE IN AVERAGE RATING"
FROM CTE2
;


            
--Catergorise customers as being:
-----Mobile App Superfans if the difference is greater than or equal to 2 in the Mobile App's favour
-----CURRENT_DATEMobile App Fans if difference >= 1
-----Online Interface Fan
-----Online Interface Superfan
-----Neutral if difference is between 0 and 1


WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID),
    CTE2 AS (SELECT CTE.CUSTOMER_ID,
                    CTE.CATEGORY,
                    "'MOBILE_APP'" "MOBILE APP",
                    "'ONLINE_INTERFACE'" "ONLINE INTERFACE",
                    AVG("MOBILE APP") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING MOBILE APP",
                    AVG("ONLINE INTERFACE") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING ONLINE INTERFACE",
                    "AVERAGE RATING MOBILE APP" - "AVERAGE RATING ONLINE INTERFACE" "DIFFERENCE IN AVERAGE RATING"
            FROM CTE
            PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
            WHERE CATEGORY <> 'OVERALL_RATING'
            GROUP BY 1,2,3,4
            ORDER BY CUSTOMER_ID)
SELECT CUSTOMER_ID,
        "DIFFERENCE IN AVERAGE RATING",
        CASE 
        WHEN "DIFFERENCE IN AVERAGE RATING" >= 2 THEN 'Mobile App Superfan'
        WHEN "DIFFERENCE IN AVERAGE RATING" >= 1 THEN 'Mobile App Fan'
        WHEN "DIFFERENCE IN AVERAGE RATING" >= 0 THEN 'Neutral'
        WHEN "DIFFERENCE IN AVERAGE RATING" <= -1 THEN 'Online Interface Fan'
        WHEN "DIFFERENCE IN AVERAGE RATING" <= -2 THEN 'Online Interface Superfan'
        WHEN "DIFFERENCE IN AVERAGE RATING" <= 0 THEN 'Neutral'
        END "Preference"
FROM CTE2
GROUP BY ALL
;



--Calculate the Percent of Total customers in each category, rounded to 1 decimal place

WITH CTE AS (SELECT CUSTOMER_ID,
                    SPLIT_PART(TYPE, '___', 1) PLATFORM,
                    SPLIT_PART(TYPE, '___', 2) CATEGORY,
                    RATING
            FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
            UNPIVOT(RATING FOR TYPE IN (MOBILE_APP___EASE_OF_USE, MOBILE_APP___EASE_OF_ACCESS, MOBILE_APP___NAVIGATION, MOBILE_APP___LIKELIHOOD_TO_RECOMMEND, MOBILE_APP___OVERALL_RATING, ONLINE_INTERFACE___EASE_OF_USE, ONLINE_INTERFACE___EASE_OF_ACCESS, ONLINE_INTERFACE___NAVIGATION, ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND, ONLINE_INTERFACE___OVERALL_RATING)) 
            ORDER BY CUSTOMER_ID),
    CTE2 AS (SELECT CTE.CUSTOMER_ID,
                    CTE.CATEGORY,
                    "'MOBILE_APP'" "MOBILE APP",
                    "'ONLINE_INTERFACE'" "ONLINE INTERFACE",
                    AVG("MOBILE APP") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING MOBILE APP",
                    AVG("ONLINE INTERFACE") OVER (PARTITION BY CTE.CUSTOMER_ID) "AVERAGE RATING ONLINE INTERFACE",
                    "AVERAGE RATING MOBILE APP" - "AVERAGE RATING ONLINE INTERFACE" "DIFFERENCE IN AVERAGE RATING"
            FROM CTE
            PIVOT (SUM(RATING) FOR PLATFORM IN ('MOBILE_APP', 'ONLINE_INTERFACE'))
            WHERE CATEGORY <> 'OVERALL_RATING'
            GROUP BY 1,2,3,4
            ORDER BY CUSTOMER_ID),
    CTE3 AS (SELECT CUSTOMER_ID,
                    "DIFFERENCE IN AVERAGE RATING",
                    CASE 
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 2 THEN 'Mobile App Superfan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 1 THEN 'Mobile App Fan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" >= 0 THEN 'Neutral'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= -1 THEN 'Online Interface Fan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= -2 THEN 'Online Interface Superfan'
                    WHEN "DIFFERENCE IN AVERAGE RATING" <= 0 THEN 'Neutral'
                    END "Preference"
            FROM CTE2
            GROUP BY ALL)
SELECT "Preference",
        ROUND((COUNT(CUSTOMER_ID) / (SELECT COUNT(CUSTOMER_ID)
                              FROM CTE3) *100) , 1) "% of Total"
FROM CTE3
GROUP BY 1
ORDER BY 2 DESC
;